name: "Find Jira Issue"
description: "find jira issue"
author: "bouzuya"
inputs:
  jira-api-token:
    description: "Jira API Token. Example: `fCKprkgrUManNx2Qc7SKkXkW`"
    required: true
  jira-base-url:
    description: "Jira URL. Example: `https://<yourdomain>.atlassian.net`"
    required: true
  jira-user-email:
    description: "Jira User Email. Example: `info@example.com`"
    required: true
  string:
    description: "A string containing the issue key. Example: `refs/heads/PRJ-1`"
    required: true
outputs:
  key:
    description: "The key of the issue found. If not found, empty string."
  summary:
    description: "The summary of the issue found. If not found, empty string."
runs:
  using: "node12"
  main: "dist/index.js"
